# Generated by Django 4.2.5 on 2023-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_clean', models.CharField(max_length=5000)),
                ('keyword', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_link', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
