# Generated by Django 4.2.5 on 2023-09-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
